# Generated by Django 2.0.6 on 2018-07-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
    ]
