# Generated by Django 2.0.6 on 2018-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alumpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumpost',
            name='views',
        ),
        migrations.AddField(
            model_name='alumpost',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
