# Generated by Django 2.0.6 on 2018-08-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180715_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumPost',
        ),
    ]
