# Generated by Django 2.0.6 on 2018-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final Time', verbose_name='Final time')),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Textaul Notes', null=True, verbose_name='Textual Notes')),
            ],
        ),
    ]
