# Generated by Django 2.0.6 on 2018-08-12 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumpost',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alum_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
