# Generated by Django 2.0.6 on 2018-08-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumpost_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumpost',
            name='image',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
