# Generated by Django 2.0.6 on 2018-08-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180812_0842'),
        ('alumni', '0004_auto_20180812_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumpost',
            name='grad_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='accounts.Alumni'),
        ),
    ]
