# Generated by Django 2.0.6 on 2018-08-25 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20180825_1137'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemRequirements',
            new_name='ItemRequirement',
        ),
    ]
