# Generated by Django 2.0.6 on 2018-08-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=15)),
                ('product', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requirements', to='products.Product')),
            ],
        ),
    ]
