# Generated by Django 2.0.6 on 2018-08-12 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_itemrequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequirements',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requirements', to=settings.AUTH_USER_MODEL),
        ),
    ]
