# Generated by Django 2.0.6 on 2018-08-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_itemrequirements_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequirements',
            name='product',
        ),
        migrations.RemoveField(
            model_name='itemrequirements',
            name='user',
        ),
        migrations.DeleteModel(
            name='ItemRequirements',
        ),
    ]
